[2024-11-26T18:38:31.568+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-26T18:38:31.599+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_submit_example_dag.spark_submit_task manual__2024-11-26T18:33:03.815961+00:00 [queued]>
[2024-11-26T18:38:31.611+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_submit_example_dag.spark_submit_task manual__2024-11-26T18:33:03.815961+00:00 [queued]>
[2024-11-26T18:38:31.613+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-11-26T18:38:31.633+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2024-11-26 18:33:03.815961+00:00
[2024-11-26T18:38:31.646+0000] {warnings.py:112} WARNING - /opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=136) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-26T18:38:31.649+0000] {standard_task_runner.py:72} INFO - Started process 138 to run task
[2024-11-26T18:38:31.650+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'spark_submit_example_dag', 'spark_submit_task', 'manual__2024-11-26T18:33:03.815961+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/spark_submit_example_dag.py', '--cfg-path', '/tmp/tmp99x8cphy']
[2024-11-26T18:38:31.651+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask spark_submit_task
[2024-11-26T18:38:31.760+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_submit_example_dag.spark_submit_task manual__2024-11-26T18:33:03.815961+00:00 [running]> on host 3d57ca4f7d74
[2024-11-26T18:38:31.891+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_submit_example_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T18:33:03.815961+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T18:33:03.815961+00:00'
[2024-11-26T18:38:31.893+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-26T18:38:31.893+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-26T18:38:31.893+0000] {logging_mixin.py:190} INFO - Current task name:spark_submit_task state:running start_date:2024-11-26 18:38:31.599432+00:00
[2024-11-26T18:38:31.893+0000] {logging_mixin.py:190} INFO - Dag name:spark_submit_example_dag and current dag run status:running
[2024-11-26T18:38:31.894+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-26T18:38:31.914+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-11-26T18:38:31.917+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.app.name=SparkSubmitExample --name spark_submit_example_job --verbose --queue root.default /opt/bitnami/airflow/dags/spark_app.py
[2024-11-26T18:38:32.141+0000] {spark_submit.py:634} INFO - JAVA_HOME is not set
[2024-11-26T18:38:32.497+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.app.name=SparkSubmitExample --name spark_submit_example_job --verbose --queue root.default /opt/bitnami/airflow/dags/spark_app.py. Error code is: 1.
[2024-11-26T18:38:32.531+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-26T18:38:32.532+0000] {logging_mixin.py:190} INFO - Task start:2024-11-26 18:38:31.599432+00:00 end:2024-11-26 18:38:32.530782+00:00 duration:0.93135
[2024-11-26T18:38:32.534+0000] {logging_mixin.py:190} INFO - Task:<Task(SparkSubmitOperator): spark_submit_task> dag:<DAG: spark_submit_example_dag> dagrun:<DagRun spark_submit_example_dag @ 2024-11-26 18:33:03.815961+00:00: manual__2024-11-26T18:33:03.815961+00:00, state:running, queued_at: 2024-11-26 18:33:03.896660+00:00. externally triggered: True>
[2024-11-26T18:38:32.536+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.app.name=SparkSubmitExample --name spark_submit_example_job --verbose --queue root.default /opt/bitnami/airflow/dags/spark_app.py. Error code is: 1.
[2024-11-26T18:38:32.538+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_submit_example_dag, task_id=spark_submit_task, run_id=manual__2024-11-26T18:33:03.815961+00:00, execution_date=20241126T183303, start_date=20241126T183831, end_date=20241126T183832
[2024-11-26T18:38:32.597+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-26T18:38:32.598+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 48 for task spark_submit_task (Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.app.name=SparkSubmitExample --name spark_submit_example_job --verbose --queue root.default /opt/bitnami/airflow/dags/spark_app.py. Error code is: 1.; 138)
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.app.name=SparkSubmitExample --name spark_submit_example_job --verbose --queue root.default /opt/bitnami/airflow/dags/spark_app.py. Error code is: 1.
[2024-11-26T18:38:32.633+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-26T18:38:32.673+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T18:38:32.675+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
